id = "yarn-spinner"
name = "Yarn Spinner"
version = "0.0.11"
schema_version = 1
authors = ["MaoT"]
description = "Yarn Spinner language support for Zed"
repository = "https://github.com/MaoTab/YarnSpinner-Zed"

[grammars.yarn_spinner]
repository = "https://github.com/MaoTab/YarnSpinner-Zed"
rev = "cf852f87d1d1fe4fa41caa2ed1927622bf22f4c8"
path = "tree-sitter"

[language_servers.yarn-spinner-lsp]
name = "Yarn Spinner LSP"
languages = ["Yarn Spinner"]
